name: LockDown-sus-process
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy2
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: prateek-stepsecurity/harden-runner@int
        with:
          egress-policy: audit
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Curl google
        run: "curl -s https://google.com"

      - name: grep test /proc/1/environ
        run: sudo grep test /proc/1/environ
                  
      - name: Curl youtube
        if: always()
        run: "curl -s https://youtube.com"

      - name: sleep 2
        if: always()
        run: sleep 2

      - name: Compress agent log
        if: always()
        continue-on-error: true
        run: |
          gzip -c /home/agent/agent.log > agent-log-${{ runner.name }}.gz

      - name: Upload agent log
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: agent-log-${{ runner.name }}
          path: agent-log-${{ runner.name }}.gz
          compression-level: 0
          retention-days: 1
